version: "3.6"
services:

  wordpress:
    image: wordpress:${WP_VER}
    container_name: wp-wordpress
    environment:
      - WORDPRESS_DB_HOST=${WP_DB_HOST}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=wp_
    ports:
      - 8080:80
    volumes:
      - ${WP_VOL}:/var/www/html
    networks:
      - net
    restart: always
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mariadb:11.1.3
    container_name: wp-db
    environment:
      - MYSQL_ROOT_PASSWORD=${WP_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: wp-phpmyadmin
    environment:
      - PMA_HOST=${WP_DB_HOST}
      - MYSQL_ROOT_PASSWORD={WP_MYSQL_ROOT_PASSWORD}
    ports:
      - 8180:80
    networks:
      - net
    restart: always
    depends_on:
      - db

volumes:
  db_data:

networks:
  net:
